source 'https://github.com/CocoaPods/Specs.git'

target 'NYTPhotoViewer', :exclusive => true do
  pod "NYTPhotoViewer/AnimatedGifSupport", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "NYTPhotoViewer/AnimatedGifSupport", :path => "../"
  pod 'OCMock', '~> 3.2'
end

target 'NYTPhotoViewer-Swift', :exclusive => true do
    pod "NYTPhotoViewer/AnimatedGifSupport", :path => "../"
end
