source 'https://github.com/CocoaPods/Specs.git'

target 'ios-photo-viewer', :exclusive => true do
  pod "NYTPhotoViewer", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "NYTPhotoViewer", :path => "../"

  
end
