#!/usr/bin/env sh

set -eu

if ! command -v bundle > /dev/null; then
  printf 'bundler is not installed.\n'
  printf 'install with $ gem install bundler\n'
  exit 1
fi

cd "$(dirname "$0")/../Examples"

bundle config set path 'vendor/bundle'
bundle install 

pod install