#!/usr/bin/env sh

set -eu
set -o pipefail

if ! command -v bundle > /dev/null; then
  printf 'bundler is not installed.\n'
  printf 'install with $ gem install bundler\n'
  exit 1
fi

cd "$(dirname "$0")/../Examples"

# uncomment the following if you get errors about not having access to the system's install
# bundle config --local path 'vendor/bundle'

bundle install 
bundle exec pod install
